pinv_rel – ForInv
pinv_rel Function
Seyed Ali Ghasemi
19 statements
Source File
private pure function pinv_rel(A, method, tol) result(Apinv)
Calculates the pseudoinverse of a matrix A.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), dimension(:, :), contiguous :: A
character(len=*), intent(in), optional :: method
real(kind=rk), intent(in), optional :: tol
Return Value real(kind=rk), dimension(size(A,2), size(A,1))
Calls
Called by
Source Code
   pure function pinv_rel(A, method, tol) result(Apinv)
#elif defined (IMPURE)
   impure function pinv_rel(A, method, tol) result(Apinv)
#endif
      ! Inputs:
      real(rk),     dimension(:, :), contiguous, intent(in) :: A
      real(rk),     intent(in), optional                    :: tol
      character(*), intent(in), optional                    :: method
      ! Outputs:
      real(rk), dimension(size(A,2), size(A,1))          :: Apinv ! Pseudoinverse of A
      if (present(method)) then
         select case (method)
            case('gesvd','gesdd')
            Apinv = pinvSVD_rel(A, method, tol)
            case('getrf')
            Apinv = pinvLU_rel(A)
            case default
            error stop 'method is not valid.'
         end select
      else
         Apinv = pinvSVD_rel(A, tol=tol)
      end if
   end function pinv_rel
Call graph
pinv_rel calls pinvlu_rel, pinvsvd_rel
pinvlu_rel calls gemm, invlu_rel
pinvsvd_rel calls svd
inv calls pinv_rel
test1 calls inv
test2 calls inv
test3 calls inv