pinv – ForInv
pinv Interface
3 statements
Source File
public interface pinv
Calls
Called by
Contents
Module Procedures
pinv_rel
Module Procedures
private pure function pinv_rel(A, method, tol) result(Apinv)
Author
Seyed Ali Ghasemi
Calculates the pseudoinverse of a matrix A.
Arguments
Type Intent Optional Attributes Name
real(kind=rk), intent(in), dimension(:, :), contiguous :: A
character(len=*), intent(in), optional :: method
real(kind=rk), intent(in), optional :: tol
Return Value real(kind=rk), dimension(size(A,2), size(A,1))
Call graph
pinv calls pinv_rel
pinv_rel calls pinvlu_rel, pinvsvd_rel
pinvlu_rel calls gemm, invlu_rel
pinvsvd_rel calls svd
test1 calls pinv
test2 calls pinv
test3 calls pinv